setwd('/Users/rincygeorge/Desktop')
install.packages("arulesViz")
install.packages("arules")
library(arules)
library(arulesViz)
data <- read.transactions("basket.csv",format="basket", sep=",")
data
summary(data)
itemFrequencyPlot(data,support= 0.06, horiz=TRUE, type="relative",top=10)
rules <- apriori(data, parameter = list(support = 0.04, confidence = 0.5))
inspect(rules)
topFiveRules <- head(sort(rules, by = "lift", decreasing = TRUE),5)
inspect(topFiveRules)
topEightRules <- head(sort(rules, by = "lift", decreasing = TRUE),8)
plot(topEightRules, method = "graph")
